class Jets::Builders
  autoload :CodeBuilder, "jets/builders/code_builder"
  autoload :CodeSize, "jets/builders/code_size"
  autoload :GemReplacer, "jets/builders/gem_replacer"
  autoload :HandlerGenerator, "jets/builders/handler_generator"
  autoload :LambdaLayer, "jets/builders/lambda_layer"
  autoload :Md5, "jets/builders/md5"
  autoload :Md5Zip, "jets/builders/md5_zip"
  autoload :Purger, "jets/builders/purger"
  autoload :RackPackager, "jets/builders/rack_packager"
  autoload :ReconfigureRails, "jets/builders/reconfigure_rails"
  autoload :RubyPackager, "jets/builders/ruby_packager"
  autoload :ShimVars, "jets/builders/shim_vars"
  autoload :Tidy, "jets/builders/tidy"
  autoload :Util, "jets/builders/util"
end
