module Jets::Commands
  autoload :Base, "jets/commands/base"
  autoload :Build, "jets/commands/build"
  autoload :Deploy, "jets/commands/deploy"
  autoload :Delete, "jets/commands/delete"
  autoload :New, "jets/commands/new"
  autoload :Call, "jets/commands/call"
  autoload :Console, "jets/commands/console"
  autoload :Db, "jets/commands/db"
  autoload :Dynamodb, "jets/commands/dynamodb"
  autoload :Main, "jets/commands/main"
  autoload :Process, "jets/commands/process"
  autoload :RakeCommand, "jets/commands/rake_command"
  autoload :Sequence, "jets/commands/sequence"
end
