#!/usr/bin/env ruby

# traps: INT - ^C
['INT', 'TERM', 'QUIT'].each do |signal|
  trap(signal) do
    puts ""
    sleep 0.1
    exit
  end
end

$:.unshift(File.expand_path("../../lib", __FILE__))
require "jets"
Jets::CLI.start
