#!/usr/bin/env ruby
# frozen_string_literal: true

# traps: INT - ^C
['INT', 'TERM', 'QUIT'].each do |signal|
  trap(signal) do
    puts "Detected stop signal"
    sleep 0.2
    exit
  end
end

$:.unshift(File.expand_path("../../lib", __FILE__))
require "jets"
Jets::CLI.start
